namespace Shared.Employee.DTO.Info
{
    public class EmployeeUploadInformation
    {
        public string EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string GlobalID { get; set; }
        public string PreviousCode { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string BranchId { get; set; }
        public string DivisionId { get; set; }
        public string UnitId { get; set; }
        public string CostCenterId { get; set; }
        public string GradeId { get; set; }
        public string DesignationId { get; set; }
        public string DepartmentId { get; set; }
        public string SectionId { get; set; }
        public string SubSectionId { get; set; }
        public string JobCategoryId { get; set; }
        public string EmployeeTypeId { get; set; }
        public string JoiningDate { get; set; }
        public string ConfirmationDate { get; set; }
        public string AppointmentDate { get; set; }
        public string ProbationEndDate { get; set; }
        public string ContractEndDate { get; set; }
        public string PFActivationDate { get; set; }
        public string LastWorkingDate { get; set; }
        public string OfficeMobile { get; set; }
        public string OfficeEmail { get; set; }
        public string ReferenceId { get; set; }
        public string FingureId { get; set; }
        public string JobType { get; set; }
        public string WorkShiftId { get; set; }
        public string SupervisorID { get; set; }
        public string HODID { get; set; }
        public string NID { get; set; }
        public string TIN { get; set; }
        public string DrivingLicense { get; set; }
        public string Passport { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string NumberOfChild { get; set; }
        public string BloodGroup { get; set; }
        public string IsResidential { get; set; }
        public string PersonalMobileNumber { get; set; }
        public string PersonalEmail { get; set; }
        public string AlternativeEmailAddress { get; set; }
        public string PresentAddress { get; set; }
        public string PresentAddressCity { get; set; }
        public string PresentAddressContactNo { get; set; }
        public string PresentAddressZipCode { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentAddressDistrict { get; set; }
        public string PermanentAddressUpazila { get; set; }
        public string PermanentAddressZipCode { get; set; }
        public string PermanentAddressContactNumber { get; set; }
        public string EmergencyContactPerson1 { get; set; }
        public string RelationWithEmergencyContactPerson1 { get; set; }
        public string EmergencyContactNoPerson1 { get; set; }
        public string EmergencyContactAddressPerson1 { get; set; }
        public string EmergencyContactEmailAddressPerson1 { get; set; }
        public string EmergencyContactPerson2 { get; set; }
        public string RelationWithEmergencyContactPerson2 { get; set; }
        public string EmergencyContactNoPerson2 { get; set; }
        public string EmergencyContactAddressPerson2 { get; set; }
        public string EmergencyContactEmailAddressPerson2 { get; set; }
        public string BankId { get; set; }
        public string BankBranchId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountActivationDate { get; set; }
        public string GrossSalary { get; set; }
        public string BasicSalary { get; set; }
        public string SalaryEffectiveDate { get; set; }
        public string SalaryActivationDate { get; set; }
        // Payment Method
        public string PaymentMode { get; set; }
        public string InternalDesignationId { get; set; }
    }
}
