// <auto-generated />
using System;
using DAL.Context.Separation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Context.Separation.Migrations
{
    [DbContext(typeof(SeparationModuleDbContext))]
    [Migration("20240525174043_Separation Module Init 25 May, 2024")]
    partial class SeparationModuleInit25May2024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.AdminResignationRequestApproval", b =>
                {
                    b.Property<long>("AdminResignationRequestApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminResignationRequestApprovalId"));

                    b.Property<string>("ApprovalRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmployeeExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HRComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFilesUpload")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInterviewDone")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPullback")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSetupComplete")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonforPullback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("RescheduleExitInterview")
                        .HasColumnType("bit");

                    b.Property<string>("ResignCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("TakeInterview")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminResignationRequestApprovalId");

                    b.ToTable("HR_AdminResignationRequestApproval");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.EmployeeResignationRequest", b =>
                {
                    b.Property<long>("ResignationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResignationRequestId"));

                    b.Property<DateTime?>("AcceptedLastWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActualFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ActualLastWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActualShortfall")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedShortfall")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployeeExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HRExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HRStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsResignationLetterUpload")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NoticeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoticePeriod")
                        .HasColumnType("int");

                    b.Property<bool?>("NotifiedWithinNoticePeriod")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RequestLastWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RescheduleExitInterviewByHR")
                        .HasColumnType("bit");

                    b.Property<bool?>("RescheduleExitInterviewBySupervisor")
                        .HasColumnType("bit");

                    b.Property<string>("ResignCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResignationCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResignationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResignationSubCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecondaryReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SupervisorExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<string>("SupervisorStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResignationRequestId");

                    b.ToTable("HR_EmployeeResignationRequest");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Resignation.EmployeeResignationDetail", b =>
                {
                    b.Property<long>("ResignationDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResignationDetailId"));

                    b.Property<string>("ApprovalRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HRComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HRExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HRInterviewRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFilesUpload")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInterviewDoneByHR")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInterviewQuestionsDoneByHR")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPullback")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonforPullback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RescheduleExitInterviewByHR")
                        .HasColumnType("bit");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResignationDetailId");

                    b.ToTable("HR_EmployeeResignationDetail");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Resignation.EmployeeResignationFile", b =>
                {
                    b.Property<long>("ResignationFilesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResignationFilesId"));

                    b.Property<string>("ActualFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AdminResignationRequestApprovalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResignationFilesId");

                    b.ToTable("HR_EmployeeResignationFiles");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Resignation.ResignationInterviewQuestion", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuestionId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionId");

                    b.ToTable("HR_ResignationInterviewQuestion");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.ResignationCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("HR_ResignationCategory");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.ResignationCategoryConfig", b =>
                {
                    b.Property<long>("ResignationConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResignationConfigId"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("NoticePeriod")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResignationConfigId");

                    b.ToTable("HR_ResignationCategoryConfig");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.ResignationSubCategory", b =>
                {
                    b.Property<long>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubCategoryId"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SubCategoryId");

                    b.ToTable("HR_ResignationSubCategory");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Settlement.EmployeeSettlementAllowance", b =>
                {
                    b.Property<int>("SettlementAllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementAllowanceId"));

                    b.Property<int?>("AllowanceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DueAllowanceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SettlementId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SettlementAllowanceId");

                    b.ToTable("Payroll_EmployeeSettlementAllowance");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Settlement.EmployeeSettlementDeduction", b =>
                {
                    b.Property<int>("SettlementDeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementDeductionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeductionId")
                        .HasColumnType("int");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SettlementId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SettlementDeductionId");

                    b.ToTable("Payroll_EmployeeSettlementDeduction");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Settlement.EmployeeSettlementProcess", b =>
                {
                    b.Property<long>("SettlementProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SettlementProcessId"));

                    b.Property<decimal?>("BonusDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BonusEarningAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClearanceBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClearanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FractionalSalaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FractionalSalaryDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GFFinalizationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBonusDeduction")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGFFinalization")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLeaveEncashment")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoanAmountDeduction")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOtherDeductions")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsProvidentFundFinalization")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWPPFFinalization")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LeaveEncashmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LoanDeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OtherAllowancesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PfCompanyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PfCompanyDividendAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PfOwnAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PfOwnDividendAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SettlementSetupId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalEmployeeEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WPPFFinalizationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SettlementProcessId");

                    b.ToTable("Payroll_EmployeeSettlementProcess");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.Settlement.EmployeeSettlementSetup", b =>
                {
                    b.Property<long>("SettlementSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SettlementSetupId"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaysOfDeductedBasic")
                        .HasColumnType("int");

                    b.Property<int?>("DaysOfExtraBasic")
                        .HasColumnType("int");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFinalSettlementComplete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGotPunishment")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSalaryDisbursedWithSettlementProcess")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfExtraBasic")
                        .HasColumnType("int");

                    b.Property<string>("NoticePayBasedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("SeparatedWithSalary")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ShortfallInNoticePeriod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("WithExtraBasic")
                        .HasColumnType("bit");

                    b.HasKey("SettlementSetupId");

                    b.ToTable("Payroll_EmployeeSettlementSetup");
                });

            modelBuilder.Entity("Shared.Separation_Module.Models.Domain.SupervisorResignationRequestApproval", b =>
                {
                    b.Property<long>("SupervisorResignationRequestApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupervisorResignationRequestApprovalId"));

                    b.Property<string>("ApprovalRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancelRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmployeeExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterviewRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInterviewDone")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("RescheduleExitInterview")
                        .HasColumnType("bit");

                    b.Property<string>("ResignCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResignationRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("TakeInterview")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupervisorResignationRequestApprovalId");

                    b.ToTable("HR_SupervisorResignationRequestApproval");
                });
#pragma warning restore 612, 618
        }
    }
}
